ci: integrate uv with pytest and update test workflows
- Update fulltest and unittest workflows to use uv (https://github.com/astral-sh/uv) for Python setup and test execution
- Replace actions/setup-python with astral-sh/setup-uv to install Python and dependencies
- Use uvx command to run Python-related commands
- Update workflow syntax and structure to accommodate uv integration
- Ensure compatibility with existing test configurations and environments

diff --git a/.github/workflows/unittest.yaml b/.github/workflows/unittest.yaml
--- a/.github/workflows/unittest.yaml
+++ b/.github/workflows/unittest.yaml
@@ -2,7 +2,7 @@ name: Unit Tests
 
 on:
   pull_request_target:
-  push: 
+  push:
     branches:
       - 'main'
       - 'dev'
@@ -14,46 +14,46 @@ jobs:
     strategy:
       matrix:
         # python-version: ['3.9', '3.10', '3.11']
-        python-version: ['3.11']
+        python-version: [ '3.11' ]
 
     steps:
-    - uses: actions/checkout@v4
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-        cache: 'pip'
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -e .[test]
-        npm install -g @mermaid-js/mermaid-cli
-        playwright install --with-deps
-    - name: Test with pytest
-      run: |
-        export ALLOW_OPENAI_API_CALL=0
-        mkdir -p ~/.metagpt && cp tests/config2.yaml ~/.metagpt/config2.yaml
-        pytest | tee unittest.txt
-    - name: Show coverage report
-      run: |
-        coverage report -m
-    - name: Show failed tests and overall summary
-      run: |
-        grep -E "FAILED tests|ERROR tests|[0-9]+ passed," unittest.txt
-        failed_count=$(grep -E "FAILED tests|ERROR tests" unittest.txt | wc -l | tr -d '[:space:]')
-        if [[ $failed_count -gt 0 ]]; then
-          echo "$failed_count failed lines found! Task failed."
-          exit 1
-        fi
-    - name: Upload pytest test results
-      uses: actions/upload-artifact@v3
-      with:
-        name: pytest-results-${{ matrix.python-version }}
-        path: |
-          ./unittest.txt
-          ./htmlcov/
-          ./tests/data/rsp_cache_new.json
-        retention-days: 3
-      if: ${{ always() }}
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - name: Install the latest version of uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: "latest"
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          uvx pip install -e .[test]
+          npm install -g @mermaid-js/mermaid-cli
+          uvx playwright install --with-deps
+      - name: Test with pytest
+        run: |
+          export ALLOW_OPENAI_API_CALL=0
+          mkdir -p ~/.metagpt && cp tests/config2.yaml ~/.metagpt/config2.yaml
+          uvx pytest | tee unittest.txt
+      - name: Show coverage report
+        run: |
+          uvx coverage report -m
+      - name: Show failed tests and overall summary
+        run: |
+          grep -E "FAILED tests|ERROR tests|[0-9]+ passed," unittest.txt
+          failed_count=$(grep -E "FAILED tests|ERROR tests" unittest.txt | wc -l | tr -d '[:space:]')
+          if [[ $failed_count -gt 0 ]]; then
+            echo "$failed_count failed lines found! Task failed."
+            exit 1
+          fi
+      - name: Upload pytest test results
+        uses: actions/upload-artifact@v4.6.0
+        with:
+          name: pytest-results-${{ matrix.python-version }}
+          path: |
+            ./unittest.txt
+            ./htmlcov/
+            ./tests/data/rsp_cache_new.json
+          retention-days: 3
+        if: ${{ always() }}
